#!/bin/bash
#
# An example hook script to log commit messages
# as a 'daily highlight' in RescueTime Premium
#
# See README.md for more information
#
# To enable this hook:
#
# 1. Place this file in .git/hooks and rename to "post-commit".
#
# 2. Update the value of API_KEY below with a valid RescueTime API key.
#    [ you can generate a key at https://www.rescuetime.com/anapi/manage ]

# Ignore global post-commit hook if local has been set up.
if [ -x ./.git/hooks/post-commit ]; then
    ./.git/hooks/post-commit
else
  API_KEY=$API_KEY_RESCUETIME_GIT

  FOLDER_NAME=$(basename "$PWD")
  COMMIT_MESSAGE=$(git log -1 HEAD --pretty=format:%s)

  MESSAGE="$FOLDER_NAME - $COMMIT_MESSAGE"
  DATE_TODAY=$(date +"%Y-%m-%d")
  LABEL='Code Commit'

  if [[ ${#MESSAGE} -gt 12 ]]; then
    curl --data "key=$API_KEY&highlight_date=$DATE_TODAY&description=$MESSAGE&source=$LABEL" https://www.rescuetime.com/anapi/highlights_post
  fi
  echo
fi
